version: '2'

services:
  mongo:
    container_name: mongodb      
    image: mongo
  mongo-web:
    container_name: mongodb-web
    image: mongo-express
    links:
      - mongo
    ports:
      - "9000:8081"    
  node-api:  
    command: nodemon
    container_name: node-api    
    environment:
      - NODE_PORT=9001
    image: node-api:0.1
    links:
      - mongo
    ports:
      - "9001:9001"
    working_dir: /node-api