version: '2'

services:
  mongodb:
    container_name: mongodb      
    image: mongo
  mongodb-web:
    container_name: mongodb-web
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    image: mongo-express
    links:
      - mongodb
    ports:
      - "9000:8081"
  node-api:  
    command: nodemon /node-api/server.js
    container_name: node-api    
    depends_on:
      - mongodb
    environment:
      - NODE_PORT=9001
    image: node-api:0.1
    links:
      - mongodb
    ports:
      - "9001:9001"      